/* Generated By:JavaCC: Do not edit this line. WoodpeckerParserConstants.java */
package edu.ecnu.woodpecker.executor.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WoodpeckerParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GET_CONN = 6;
  /** RegularExpression Id. */
  int GET_STAT = 7;
  /** RegularExpression Id. */
  int GET_PSTAT = 8;
  /** RegularExpression Id. */
  int GET_CSTAT = 9;
  /** RegularExpression Id. */
  int SQL = 10;
  /** RegularExpression Id. */
  int PSQL = 11;
  /** RegularExpression Id. */
  int CSQL = 12;
  /** RegularExpression Id. */
  int TX = 13;
  /** RegularExpression Id. */
  int VERIFY = 14;
  /** RegularExpression Id. */
  int SLEEP = 15;
  /** RegularExpression Id. */
  int ST = 16;
  /** RegularExpression Id. */
  int IMPORT_DBI = 17;
  /** RegularExpression Id. */
  int CLEAR_DBI = 18;
  /** RegularExpression Id. */
  int IMPORT_IRS = 19;
  /** RegularExpression Id. */
  int SYS = 20;
  /** RegularExpression Id. */
  int DEF_PROC = 21;
  /** RegularExpression Id. */
  int CONTAIN = 22;
  /** RegularExpression Id. */
  int CAL = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int ELSE = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int ERROR = 27;
  /** RegularExpression Id. */
  int INDEX_OF = 28;
  /** RegularExpression Id. */
  int GRD = 29;
  /** RegularExpression Id. */
  int CPU = 30;
  /** RegularExpression Id. */
  int MEM = 31;
  /** RegularExpression Id. */
  int DISK = 32;
  /** RegularExpression Id. */
  int NET = 33;
  /** RegularExpression Id. */
  int TABLE = 34;
  /** RegularExpression Id. */
  int COLUMN = 35;
  /** RegularExpression Id. */
  int IMPORT_TBL = 36;
  /** RegularExpression Id. */
  int CLEAR_TBL = 37;
  /** RegularExpression Id. */
  int TXN = 38;
  /** RegularExpression Id. */
  int END_TXN = 39;
  /** RegularExpression Id. */
  int TXN_LOADING = 40;
  /** RegularExpression Id. */
  int MULTIPLE = 41;
  /** RegularExpression Id. */
  int END_MULTIPLE = 42;
  /** RegularExpression Id. */
  int BRANCH = 43;
  /** RegularExpression Id. */
  int BRANCH_DELIMITER = 44;
  /** RegularExpression Id. */
  int END_BRANCH = 45;
  /** RegularExpression Id. */
  int INSERT = 46;
  /** RegularExpression Id. */
  int REPLACE = 47;
  /** RegularExpression Id. */
  int SELECT = 48;
  /** RegularExpression Id. */
  int DELETE = 49;
  /** RegularExpression Id. */
  int UPDATE = 50;
  /** RegularExpression Id. */
  int SelectForUpdate = 51;
  /** RegularExpression Id. */
  int PARALL = 52;
  /** RegularExpression Id. */
  int MID_PARALL = 53;
  /** RegularExpression Id. */
  int END_PARALL = 54;
  /** RegularExpression Id. */
  int BOOLEAN = 55;
  /** RegularExpression Id. */
  int BYTE = 56;
  /** RegularExpression Id. */
  int CHAR = 57;
  /** RegularExpression Id. */
  int DOUBLE = 58;
  /** RegularExpression Id. */
  int FLOAT = 59;
  /** RegularExpression Id. */
  int INT = 60;
  /** RegularExpression Id. */
  int LONG = 61;
  /** RegularExpression Id. */
  int SHORT = 62;
  /** RegularExpression Id. */
  int STRING = 63;
  /** RegularExpression Id. */
  int DECIMAL = 64;
  /** RegularExpression Id. */
  int CONNECTION = 65;
  /** RegularExpression Id. */
  int STATEMENT = 66;
  /** RegularExpression Id. */
  int PSTATEMENT = 67;
  /** RegularExpression Id. */
  int CSTATEMENT = 68;
  /** RegularExpression Id. */
  int LIST = 69;
  /** RegularExpression Id. */
  int RESULTSET = 70;
  /** RegularExpression Id. */
  int IDEALRESULTSET = 71;
  /** RegularExpression Id. */
  int PERFORMANCERESULT = 72;
  /** RegularExpression Id. */
  int TIMESTAMP = 73;
  /** RegularExpression Id. */
  int VARCHAR = 74;
  /** RegularExpression Id. */
  int MS_CATEGORY = 75;
  /** RegularExpression Id. */
  int TX_OP = 76;
  /** RegularExpression Id. */
  int TIME_UNIT = 77;
  /** RegularExpression Id. */
  int IP_ADDRESS = 78;
  /** RegularExpression Id. */
  int IS_CLUSTER_AVAILABLE = 79;
  /** RegularExpression Id. */
  int AWAIT_AVAILABLE = 80;
  /** RegularExpression Id. */
  int MERGE = 81;
  /** RegularExpression Id. */
  int IS_MERGE_DONE = 82;
  /** RegularExpression Id. */
  int AWAIT_MERGE_DONE = 83;
  /** RegularExpression Id. */
  int REELECT = 84;
  /** RegularExpression Id. */
  int EXIST_MASTER = 85;
  /** RegularExpression Id. */
  int KILL_SERVER = 86;
  /** RegularExpression Id. */
  int START_SERVER = 87;
  /** RegularExpression Id. */
  int ADD_SERVER = 88;
  /** RegularExpression Id. */
  int SET_MASTER = 89;
  /** RegularExpression Id. */
  int GATHER_STATISTICS = 90;
  /** RegularExpression Id. */
  int IS_GATHER_DONE = 91;
  /** RegularExpression Id. */
  int SERVER_OPTION = 92;
  /** RegularExpression Id. */
  int PROCEDURE_PARAM_TYPE = 93;
  /** RegularExpression Id. */
  int PK = 94;
  /** RegularExpression Id. */
  int RESULT_HANDLE = 95;
  /** RegularExpression Id. */
  int EXECUTE_TYPE = 96;
  /** RegularExpression Id. */
  int SET_TYPE = 97;
  /** RegularExpression Id. */
  int FK = 98;
  /** RegularExpression Id. */
  int INDEX = 99;
  /** RegularExpression Id. */
  int FILTER = 100;
  /** RegularExpression Id. */
  int APPEND = 101;
  /** RegularExpression Id. */
  int DISTRIBUTION_TYPE = 102;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 103;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 104;
  /** RegularExpression Id. */
  int HEX_LITERAL = 105;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 106;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 107;
  /** RegularExpression Id. */
  int EXPONENT = 108;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 109;
  /** RegularExpression Id. */
  int TRUE = 110;
  /** RegularExpression Id. */
  int FALSE = 111;
  /** RegularExpression Id. */
  int NULL = 112;
  /** RegularExpression Id. */
  int CALCULATION = 113;
  /** RegularExpression Id. */
  int LPAREN = 114;
  /** RegularExpression Id. */
  int RPAREN = 115;
  /** RegularExpression Id. */
  int LBRACE = 116;
  /** RegularExpression Id. */
  int RBRACE = 117;
  /** RegularExpression Id. */
  int LBRACKET = 118;
  /** RegularExpression Id. */
  int RBRACKET = 119;
  /** RegularExpression Id. */
  int SEMICOLON = 120;
  /** RegularExpression Id. */
  int COMMA = 121;
  /** RegularExpression Id. */
  int DOT = 122;
  /** RegularExpression Id. */
  int ASSIGN = 123;
  /** RegularExpression Id. */
  int GT = 124;
  /** RegularExpression Id. */
  int LT = 125;
  /** RegularExpression Id. */
  int BANG = 126;
  /** RegularExpression Id. */
  int TILDE = 127;
  /** RegularExpression Id. */
  int HOOK = 128;
  /** RegularExpression Id. */
  int COLON = 129;
  /** RegularExpression Id. */
  int EQ = 130;
  /** RegularExpression Id. */
  int LE = 131;
  /** RegularExpression Id. */
  int GE = 132;
  /** RegularExpression Id. */
  int NE = 133;
  /** RegularExpression Id. */
  int SC_OR = 134;
  /** RegularExpression Id. */
  int SC_AND = 135;
  /** RegularExpression Id. */
  int INCR = 136;
  /** RegularExpression Id. */
  int DECR = 137;
  /** RegularExpression Id. */
  int PLUS = 138;
  /** RegularExpression Id. */
  int MINUS = 139;
  /** RegularExpression Id. */
  int STAR = 140;
  /** RegularExpression Id. */
  int SLASH = 141;
  /** RegularExpression Id. */
  int BIT_AND = 142;
  /** RegularExpression Id. */
  int BIT_OR = 143;
  /** RegularExpression Id. */
  int XOR = 144;
  /** RegularExpression Id. */
  int REM = 145;
  /** RegularExpression Id. */
  int LSHIFT = 146;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 147;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 148;
  /** RegularExpression Id. */
  int PLUSASSIGN = 149;
  /** RegularExpression Id. */
  int MINUSASSIGN = 150;
  /** RegularExpression Id. */
  int STARASSIGN = 151;
  /** RegularExpression Id. */
  int SLASHASSIGN = 152;
  /** RegularExpression Id. */
  int ANDASSIGN = 153;
  /** RegularExpression Id. */
  int ORASSIGN = 154;
  /** RegularExpression Id. */
  int XORASSIGN = 155;
  /** RegularExpression Id. */
  int REMASSIGN = 156;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 157;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 158;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 159;
  /** RegularExpression Id. */
  int LIKE = 160;
  /** RegularExpression Id. */
  int CONTAINS = 161;
  /** RegularExpression Id. */
  int ALL_ARE = 162;
  /** RegularExpression Id. */
  int IDENTIFIER = 163;
  /** RegularExpression Id. */
  int LETTER = 164;
  /** RegularExpression Id. */
  int PART_LETTER = 165;
  /** RegularExpression Id. */
  int STRING_LITERAL = 166;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"GET_CONN\"",
    "\"GET_STAT\"",
    "\"GET_PSTAT\"",
    "\"GET_CSTAT\"",
    "\"SQL\"",
    "\"PSQL\"",
    "\"CSQL\"",
    "\"TX\"",
    "\"VERIFY\"",
    "\"SLEEP\"",
    "\"ST\"",
    "\"IMPORT_DBI\"",
    "\"CLEAR_DBI\"",
    "\"IMPORT_IRS\"",
    "\"SYS\"",
    "\"DEF_PROC\"",
    "\"CONTAIN\"",
    "\"CAL\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"ERROR\"",
    "\"INDEX_OF\"",
    "\"GRD\"",
    "\"CPU\"",
    "\"MEM\"",
    "\"DISK\"",
    "\"NET\"",
    "\"TABLE\"",
    "\"COLUMN\"",
    "\"IMPORT_TBL\"",
    "\"CLEAR_TBL\"",
    "\"TXN\"",
    "\"END_TXN\"",
    "\"TXN_LOADING\"",
    "\"MULTIPLE\"",
    "\"END_MULTIPLE\"",
    "\"BRANCH\"",
    "\"BRANCH_DELIMITER\"",
    "\"END_BRANCH\"",
    "\"INSERT\"",
    "\"REPLACE\"",
    "\"SELECT\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"SelectForUpdate\"",
    "\"PARALL\"",
    "\"MID_PARALL\"",
    "\"END_PARALL\"",
    "\"boolean\"",
    "\"byte\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"short\"",
    "\"String\"",
    "\"Decimal\"",
    "\"Connection\"",
    "\"Statement\"",
    "\"PStatement\"",
    "\"CStatement\"",
    "\"List\"",
    "\"ResultSet\"",
    "\"IdealResultSet\"",
    "\"PerformanceResult\"",
    "\"Timestamp\"",
    "\"varchar\"",
    "<MS_CATEGORY>",
    "<TX_OP>",
    "<TIME_UNIT>",
    "<IP_ADDRESS>",
    "\"is_cluster_available\"",
    "\"await_available\"",
    "\"merge\"",
    "\"is_merge_done\"",
    "\"await_merge_done\"",
    "\"reelect\"",
    "\"exist_master\"",
    "\"kill_server\"",
    "\"start_server\"",
    "\"add_server\"",
    "\"set_master\"",
    "\"gather_statistics\"",
    "\"is_gather_done\"",
    "<SERVER_OPTION>",
    "<PROCEDURE_PARAM_TYPE>",
    "\"PK\"",
    "<RESULT_HANDLE>",
    "<EXECUTE_TYPE>",
    "\"set_type\"",
    "\"FK\"",
    "\"index\"",
    "\"filter\"",
    "\"append\"",
    "<DISTRIBUTION_TYPE>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<CALCULATION>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"like\"",
    "\"contains\"",
    "\"all_are\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<STRING_LITERAL>",
  };

}
