database_user = admin
database_password = admin

src_path = "10.11.1.190@/home/lijieying/git/oceanbase_alibaba"

 make_path = "10.11.1.190@/home/lijieying/installed/oceanbase"
## make_path = "10.11.1.190@/home/lijieying/installed_dev/oceanbase"

core = 20

compile_tools = false

connection_port = 22
