## 单集群部署配置文件

deploy_path = "/home/lijieying/frametest/"

## UPS第一个数字为-p，第二个为-m；MS第一个数字为-p，第二个为-z
cedar_port=RS:14500; UPS:14700,14701; MS:14800,14880; CS:14600

 10.11.1.190 = RS | UPS | CS |MS
 10.11.1.192 = MS | CS
 10.11.1.191 = RS | UPS | CS |MS
 10.11.1.193 = RS | UPS | CS |MS
 10.11.1.195 = MS | CS
 10.11.1.196 = MS | CS

log_path = "/home/lijieying/frametest/logs/"
