## 是否发行版
release = true

## MySQL安装目录，release版不可为空，RPM版可为空
MySQL_root = /home/lijieying/mysql-5.7.18

## database user and password
database_user = admin
database_password = admin

## MySQL IP
IP = 10.11.1.199

## MySQL port
port = 33306
